dist: xenial
env:
  MATRIX_EVAL="CC=clang && CXX=clang++"
language: c++
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -q
  - sudo apt-get install -y clang cmake qtbase5-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-regex-dev libasound2-dev libiberty-dev binutils-dev librtaudio-dev librtmidi-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./bin/theta_tests
