matrix:
  dist: xenial
  addons:
    apt:
      packages:
        - clang-7.0
        - cmake
        - qtbase5-dev
        - libboost-dev
        - libboost-date-time-dev
        - libboost-filesystem-dev
        - libboost-iostreams-dev
        - libboost-program-options-dev
        - libboost-regex-dev
        - libasound2-dev
        - libiberty-dev
        - binutils-dev
        - librtaudio-dev
        - librtmidi-dev
  env:
    MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./bin/theta_tests
